### ISSUE TITLE
Fix failing test on Node v18, but working on Node v20

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/service-workers-fetch-event.node#2]
## v18

```py
RUN  v0.31.0 /home/runner/work/service-workers-fetch-event.node/service-workers-fetch-event.node

stdout | unknown test
HTTP server listening on http://localhost:8080

 ❯ test/index.test.ts  (6 tests | 1 failed) 370ms
   ❯ test/index.test.ts > it forwards to static files
     → expected [50](https://github.com/jcbhmr/service-workers-fetch-event.node/actions/runs/4963635675/jobs/8883063182#step:5:51)0 to be 200 // Object.is equality
 ✓ test/internal/globalthis-eventtarget/index.test.ts  (4 tests) 6ms

⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/index.test.ts > it forwards to static files
AssertionError: expected 500 to be 200 // Object.is equality
 ❯ test/index.test.ts:11:27
      9|   const response = await fetch("http://localhost:8080/README.md");
     10|   const text = await response.text();
     11|   expect(response.status).toBe(200);
       |                           ^
     12|   expect(text.length).toBeGreaterThan(0);
     13| });

  - Expected  - 1
  + Received  + 1

  - 200
  + 500
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed | 1 passed (2)
      Tests  1 failed | 9 passed (10)
   Start at  23:01:29
   Duration  1.58s (transform 211ms, setup 0ms, collect 345ms, tests 376ms, environment 1ms, prepare 215ms)
```

## v20

```py
 RUN  v0.31.0 /workspaces/service-workers-fetch-event.node

stdout | unknown test
HTTP server listening on http://localhost:8080

 ✓ test/index.test.ts (6) 365ms
 ✓ test/internal/globalthis-eventtarget/index.test.ts (4)

 Test Files  2 passed (2)
      Tests  10 passed (10)
   Start at  23:06:47
   Duration  1.31s (transform 139ms, setup 0ms, collect 255ms, tests 373ms, environment 0ms, prepare 137ms)
```

**Comment by jcbhmr** [comment]
```py
TypeError: __vite_ssr_import_0__.openAsBlob is not a function
    at /workspaces/service-workers-fetch-event.node/src/internal/fallbackHandleRequest.ts:37:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Module.fallbackHandleRequest [as default] (/workspaces/service-workers-fetch-event.node/src/internal/fallbackHandleRequest.ts:36:25)
    at Module.handleRequest [as default] (/workspaces/service-workers-fetch-event.node/src/internal/handleRequest.ts:21:8)
```
